### ISSUE TITLE
Use uniform batch scripts

### ISSUE THREAD

**Issue by warpech** [StarcounterApps/Barcodes#12]
Use uniform batch scripts as presented in https://starcounter.gitbooks.io/guidelines/content/batch-files.html

Discussion: https://github.com/Starcounter/Guidelines/issues/6

**Comment by warpech** [comment]
According to the discussion linked above, `make.bat` and `restart.bat` should be removed.

**Comment by Mackiovello** [comment]
Fixed with 	1f1daa8. Should it be merged to master or kept to develop?

**Comment by warpech** [comment]
<img width="419" alt="screen shot 2017-03-17 at 11 13 47" src="https://cloud.githubusercontent.com/assets/566463/24038701/d18def9c-0b02-11e7-88aa-d657fbf9fda1.png">

^ this should never happen. Could you please merge from `master` to `develop`?

Thanks! All changes should go through the same cycle (https://starcounter.gitbooks.io/guidelines/content/branching.html):

1. PR
2. Merge PR to develop if it works with Starcounter RC
3. Merge develop to master if it works with Starcounter stable

**Comment by warpech** [comment]
https://github.com/StarcounterApps/Barcodes/commit/1f1daa8bd38e1105e50334c67e152f1c6fd8d6e1 is not a complete fix for #12. The scripts: `run`, `package`, `build` should be changed to be copies from the ones in Guidelines.

**Comment by Mackiovello** [comment]
> 1f1daa8 is not a complete fix for #12. The scripts: run, package, build should be changed to be copies from the ones in Guidelines.

Got it, I'll take care of the other similar issues as well

**Comment by warpech** [comment]
Great, I appreciate it!

**Comment by Mackiovello** [comment]
Fixed with 	32828ed

**Comment by Mackiovello** [comment]
Add `test.bat` that runs `test.js`

**Comment by Mackiovello** [comment]
The tests are broken. @miyconst recommended deleting them. The same applies to Skyper and possibly some more apps. 

Running the apps on two different test frameworks is not the ultimate solution either.

**Comment by warpech** [comment]
I agree, please delete them then.

**Comment by Mackiovello** [comment]
`test.js` is now deleted. Bat scripts are now following the guidelines: run, build, and package

**Comment by Mackiovello** [comment]
Fix path of exe file.

**Comment by Mackiovello** [comment]
Fixed in 5d9fc187ebe1ec8efd4a015732f44aa7c8764d5b

**Comment by warpech** [comment]
After last change the "Debug" output path is good, but the "Release" output path should be changed, too: 

https://github.com/StarcounterApps/Barcodes/blob/5d9fc187ebe1ec8efd4a015732f44aa7c8764d5b/src/Barcodes/Barcodes.csproj#L23

Is: 

```
<OutputPath>..\..\bin\Release\</OutputPath>
```

Should be:

```
<OutputPath>bin\Release\</OutputPath>
```

**Comment by Mackiovello** [comment]
Should now finally be done with 	eb5ec4e

**Comment by KmaTTi89** [comment]
https://github.com/StarcounterApps/Barcodes/pull/13
