### ISSUE TITLE
Replace juicy-style with template is="declarative-shadow-dom"

### ISSUE THREAD

**Issue by warpech** [StarcounterApps/Barcodes#9]
This task is the part of the effort to implement https://github.com/Starcounter/RebelsLounge/blob/master/app/client/layouts/longterm_solution_md.md

Support for `juicy-style` is being removed from Launcher, starting from Launcher `develop` branch.

Use Products app as reference for this task (https://github.com/StarcounterSamples/Products/issues/18)

---

In the Barcodes app, replace `juicy-style` with `template is="declarative-shadow-dom"`.

Do this on Barcodes `develop` branch. (see [branching policy](https://starcounter.gitbooks.io/guidelines/content/branching.html))

**Comment by PatrykSzwer** [comment]
Done, closing.
